plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\laksh\\Documents\\Codex\\2026-05-17\\here-s-your-complete-pdfvault-a\\pdfvault\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\laksh\\Documents\\Codex\\2026-05-17\\here-s-your-complete-pdfvault-a\\pdfvault"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]